### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by liuyuxivapor** [LaBlazer/lcd-simulator#1]
i chose `cmake -G Unix_Makefile` to generate Makefile and executable files. But it says that `it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be NOT FOUND.` I read opencv.cmake but found myself at sea. Should I trace it or try other methods? Thanks a lot!

**Comment by LaBlazer** [comment]
You'll need to install opencv and modify the cmake file to run it on linux, here are some resources https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html
https://docs.opencv.org/4.x/db/df5/tutorial_linux_gcc_cmake.html

**Comment by liuyuxivapor** [comment]
Solved! Thanks a lot!
